name: My Panda CI 
on:
  push:
    branches: [main]

jobs:
  builds:
    runs-on: ubuntu-latest
    name: my build
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5.2.0
        with: 
          go-version: 1.23.0

      - name: what is go version
        run: |
          go version
          ls
          go test -cover

      - name: Checkout repo remotely
        uses: actions/checkout@v4
        with:
          repository: icecreampoop/Github-Actions-Lesson
          path: hehe
          token: ${{ secrets.HEHE_TOKEN }}

      - name: List out hidden things
        run: |
          ls
          cd hiddenFolder
          ls
          cd ..
