name: My Panda CI 
on:
  push:
    branches: [main]

jobs:
  builds:
    runs-on: ubuntu-latest
    name: my build
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5.2.0
        with: 
          go-version: 1.23.0

      - name: what is go version
        run: |
          go version
          ls
          go test -cover

      - name: Checkout repo remotely
        uses: actions/checkout@v4
        with:
          repository: icecreampoop/Github-Actions-Lesson
          path: hehefolder
          token: ${{ secrets.HEHE_TOKEN }}

      - name: List out hidden things
        run: |
          ls
          cd hehefolder
          ls
          cd ..

      - name: discord-action
  # You may pin to the exact commit or the version.
  # uses: sebastianpopp/discord-action@4f2d5417bc61a79593304a62e71cd32427c17790
        uses: sebastianpopp/discord-action@v2.0
        with:
    # Discord webhook URL
          webhook: https://discordapp.com/api/webhooks/1316956354786885673/TnLUfOQiSbcjinGjEXP44tQwVosbe8HGv_gviHMyIZYWbWlr4rcTYRDpNk24h2DO7pa5
    # Message to be sent
          message: This is pck
          
