name: My Panda CI 
on:
  push:
    branches: [main]

jobs:
  builds:
    runs-on: ubuntu-latest
    name: my build
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5.2.0
        with: 
          go-version: 1.23.0

      - name: what is go version
        run: |
          go version
          ls
          go test -cover

      - name: Checkout repo remotely
        uses: actions/checkout@v4
        with:
          repository: icecreampoop/Github-Actions-Lesson
          path: hehefolder
          token: ${{ secrets.HEHE_TOKEN }}

      - name: List out hidden things
        run: |
          ls
          cd hehefolder
          ls
          cd ..

      - name: discord-action
        uses: discord-actions/message@v2
        with:
          webhookUrl: https://discordapp.com/api/webhooks/1316956354786885673/TnLUfOQiSbcjinGjEXP44tQwVosbe8HGv_gviHMyIZYWbWlr4rcTYRDpNk24h2DO7pa5
          message: Hi guys, this is Seb. I am hereby promoting pck to be IC5 effective 2025
          username: Le Stonk CK
          avatar: https://media.licdn.com/dms/image/v2/C5603AQHJUmjAUgp4Hw/profile-displayphoto-shrink_200_200/profile-displayphoto-shrink_200_200/0/1517673150770?e=2147483647&v=beta&t=KK4cL6u-eYyLmmoTYm5ApCKvOx_-e6iaTh8Mzz3Kulg
          
